# Generated by Django 5.2.3 on 2025-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='user_types',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('RESTAURANT', 'RESTAURANT'), ('CUSTOMER', 'CUSTOMER'), ('ADMIN', 'ADMIN')], default='SELECT'),
        ),
    ]
