# Generated by Django 6.0.3 on 2026-04-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profilemodel_user_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
