# Generated by Django 5.2.3 on 2025-08-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_fooditemsmodel_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_username', models.CharField(max_length=50)),
                ('log_prod_code', models.IntegerField(default=100)),
                ('log_item_name', models.CharField(max_length=100)),
                ('log_operation_type', models.CharField(max_length=50)),
            ],
        ),
    ]
